import { PDFDocument, PDFPage, rgb } from '@react-pdf/renderer';
import { ObjectId } from 'mongodb';
import { getDatabase } from '../db/mongodb';

export async function generateMonthlyReport(userId: string, month: number, year: number): Promise<Buffer> {
  const db = await getDatabase();
  const userObjectId = new ObjectId(userId);

  const user = await db.collection('users').findOne({ _id: userObjectId });

  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month, 0);

  const transactions = await db
    .collection('transactions')
    .find({
      userId: userObjectId,
      date: { $gte: startDate, $lte: endDate },
    })
    .sort({ date: -1 })
    .toArray();

  const totalIncome = transactions
    .filter((t) => t.type === 'income')
    .reduce((sum, t) => sum + t.amount, 0);

  const totalExpense = transactions
    .filter((t) => t.type === 'expense')
    .reduce((sum, t) => sum + t.amount, 0);

  const byCategory: Record<string, number> = {};
  transactions.forEach((t) => {
    if (t.type === 'expense') {
      byCategory[t.category] = (byCategory[t.category] || 0) + t.amount;
    }
  });

  // Simple HTML-based PDF generation (alternative to react-pdf)
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; color: #333; }
        .summary { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin-bottom: 30px; }
        .summary-card { background: #f5f5f5; padding: 15px; border-radius: 5px; }
        .summary-card p { margin: 0; color: #666; }
        .summary-card .value { font-size: 24px; font-weight: bold; margin-top: 5px; }
        .transactions { margin-top: 30px; }
        .transactions h2 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th { background: #333; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .category-breakdown { margin-top: 30px; }
        .category-breakdown h2 { color: #333; }
        .category-item { padding: 8px 0; border-bottom: 1px solid #eee; }
        .income { color: green; }
        .expense { color: red; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>MoneyMatters - Monthly Report</h1>
        <p>${new Date(year, month - 1).toLocaleString('default', { month: 'long', year: 'numeric' })}</p>
        <p>Generated for: ${user?.name || 'User'}</p>
      </div>

      <div class="summary">
        <div class="summary-card">
          <p>Total Income</p>
          <div class="value income">$${totalIncome.toFixed(2)}</div>
        </div>
        <div class="summary-card">
          <p>Total Expenses</p>
          <div class="value expense">$${totalExpense.toFixed(2)}</div>
        </div>
        <div class="summary-card">
          <p>Balance</p>
          <div class="value ${totalIncome - totalExpense >= 0 ? 'income' : 'expense'}">$${(totalIncome - totalExpense).toFixed(2)}</div>
        </div>
      </div>

      <div class="category-breakdown">
        <h2>Spending by Category</h2>
        ${Object.entries(byCategory)
          .map(
            ([category, amount]) =>
              `<div class="category-item"><strong>${category}:</strong> <span class="expense">$${(amount as number).toFixed(2)}</span></div>`
          )
          .join('')}
      </div>

      <div class="transactions">
        <h2>All Transactions</h2>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Description</th>
              <th>Category</th>
              <th>Type</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            ${transactions
              .map(
                (t) => `
              <tr>
                <td>${new Date(t.date).toLocaleDateString()}</td>
                <td>${t.description}</td>
                <td>${t.category}</td>
                <td>${t.type}</td>
                <td class="${t.type === 'income' ? 'income' : 'expense'}">
                  ${t.type === 'income' ? '+' : '-'}$${t.amount.toFixed(2)}
                </td>
              </tr>
            `
              )
              .join('')}
          </tbody>
        </table>
      </div>

      <div style="margin-top: 50px; text-align: center; color: #999; font-size: 12px;">
        <p>This is an automated report generated by MoneyMatters</p>
      </div>
    </body>
    </html>
  `;

  // For production, you'd use a library like puppeteer or html2pdf
  // This is a simplified version
  return Buffer.from(html);
}
